### PR TITLE
recent patients endpoints

### LINKED ISSUE #370: Implement `GetRecentPatients` endpoint
This endpoint should retrieve the recent patient from the LRU and returns them via the `GetRecentPatients` response. The response should be structured as [GetPatientListResponse.PatientWithRoomAndBed](https://proto.helpwave.de/#proto.services.task_svc.v1.GetPatientListResponse.PatientWithRoomAndBed)

### PR DESCRIPTION
**Pull request by FoseFx**
## Which issues does this pull request close?
closes #370

```
INSERT INTO wards VALUES ('42aedf8b-5ded-46bd-89d9-5e39ab5bbd5e', 'Ward', '1a4e06e0-39bd-49f5-84df-b358d74ee3a5');

INSERT INTO rooms VALUES ('7eb29a29-2a53-49f7-bce7-51707af1941c', 'Room', '1a4e06e0-39bd-49f5-84df-b358d74ee3a5', '42aedf8b-5ded-46bd-89d9-5e39ab5bbd5e');


INSERT INTO beds VALUES ('c6a45a73-4e7d-4bad-918d-bdb622551f88', '7eb29a29-2a53-49f7-bce7-51707af1941c', '1a4e06e0-39bd-49f5-84df-b358d74ee3a5', 'Bed 1');


INSERT INTO patients VALUES ('916867f8-302c-413f-a929-03f968beebb2', 'HRID', '1a4e06e0-39bd-49f5-84df-b358d74ee3a5', '', 'c6a45a73-4e7d-4bad-918d-bdb622551f88', 0);


```

### CODE REVIEW

**Comment by FoseFx** [comment]
_poke_

**Comment by MaxSchaefer** [comment]
@FooseFx I've added some error logging around the Add...-Operations. The implemented endpoint is looking good but I got the following error `2023-09-02T23:24:51Z app[28650eeb793498] ams [info]app   | 11:24PM ERR ../build/app/internal/tracking/tracking.go:59 > could 
not add patient to recent activity 
error="ERR Error running script: @user_script:23: bad argument #1 to random (number expected, got string) stack traceback:  [G]: in function 'random'  @user_script:23: in main chunk  [G]: ?" handler=/proto.services.task_svc.v1.PatientService/GetPatientDetails 
organizationID=3b25c6f5-4705-4074-9fc6-a50c28eba406 service=task-svc span= userID=18159713-5d4e-4ad5-94ad-fbb6bb147984 version=`.

**Comment by FoseFx** [comment]
I love me some upstash compatibility issues!

**Comment by FoseFx** [comment]
image

**Comment by MaxSchaefer** [comment]
So sorry 😅 Review is scheduled :)

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
It seems like that the `rooms` are not filled correctly

Response of `GetRecentPatients`
```json
{
    "recent_patients": [
        {
            "id": "d1612e2e-f55c-4761-ba5b-cab2c419f49a",
            "human_readable_identifier": "asd",
            "room": null,
            "bed": {
                "id": "02526385-4da1-4705-ae10-771b3d1f631d",
                "name": "asdasd"
            }
        }
    ]
}
```

**Review by MaxSchaefer — APPROVED** [review]
🤘

**Pull request merged**
