### PR TITLE
feat: add GetAllTaskTemplatesByUser endpoint

### LINKED ISSUE #212: GetAllTaskTemplatesByUser
This issue should implement the method `GetAllTaskTemplatesByUser`. Please omit the user_id and organization_id of the response.

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #212

### CODE REVIEW

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
I've got the error `Subtasks: unsupported relations for schema TaskTemplate` from the method `GetAllTaskTemplatesByUser`.

Steps to reproduce:

1. Create a ward
`CreateWard`
```json
{
    "name": "Ward One"
}
```
2. Create a task template with that ward id
`CreateTaskTemplate`
```json
{
    "name": "lel",
    "description": "asd",
    "ward_id": "731b19f0-c6a8-4b7e-a31a-49955b74dcce"
}
```
3. Use the new method
`GetAllTaskTemplatesByUser`
```json
{
    "user_id": "18159713-5d4e-4ad5-94ad-fbb6bb147984"
}
```
Then an error occurred. All migrations are done.

**Comment by MaxSchaefer** [comment]
I've also updated all issues with specific implementation details like this one
> Please omit the user_id and organization_id of the response.

**Comment by MaxSchaefer** [comment]
fyi: Same error on all Read endpoints right now. @FoseFx you do not have this error?

**Comment by DasProffi** [comment]
> I've got the error `Subtasks: unsupported relations for schema TaskTemplate` from the method `GetAllTaskTemplatesByUser`.
> 
> Steps to reproduce:
> 
> 1. Create a ward
>    `CreateWard`
> 
> ```json
> {
>     "name": "Ward One"
> }
> ```
> 
> 2. Create a task template with that ward id
>    `CreateTaskTemplate`
> 
> ```json
> {
>     "name": "lel",
>     "description": "asd",
>     "ward_id": "731b19f0-c6a8-4b7e-a31a-49955b74dcce"
> }
> ```
> 
> 3. Use the new method
>    `GetAllTaskTemplatesByUser`
> 
> ```json
> {
>     "user_id": "18159713-5d4e-4ad5-94ad-fbb6bb147984"
> }
> ```
> 
> Then an error occurred. All migrations are done.

Solved, it is the string in the preload, that doesn't match the struct name due to a typo

**Review by MaxSchaefer — APPROVED** [review]

**Pull request merged**
