### PR TITLE
remove keycloak

### PR DESCRIPTION
**Pull request by FoseFx**
Blocked by #139

I kept the cert and coredns deployments for future use

### CODE REVIEW

**Comment by MaxSchaefer** [comment]
@FoseFx thanks! Nice clean-up 🧹 I guess it makes sense to [add the required envs](https://github.com/helpwave/services/blob/main/libs/common/auth.go#LL61C4-L61C4) for auth related stuff as well.

**Comment by FoseFx** [comment]
I think the lint errors are due to #136?

**Comment by MaxSchaefer** [comment]
> I think the lint errors are due to #136?

Yes. Breaking changes in the defition. It looks like that these breaking changes occured int the `room-svc`. You can either fix these issues in this pr or wait for #147 with this pr in draft. I'll prefer the first option.

**Comment by use-to** [comment]
Our action detecting changed files is not working correctly.
This error should have occurred right after we updated protobuf definitions.

**Review by MaxSchaefer — APPROVED** [review]

**Pull request merged**
