### PR TITLE
add breadcrumb service

### LINKED ISSUE #366: Resolving breadcrumbs
### Describe the feature

This issue should introduce the gRPC service `BreadcrumbService` inside the `task-svc` microservice. The implementation of this gRPC service should resolve the necessary information based on the relations between the entities. I've already created a `.proto` file, _see Additional context_.

For example, if the caller passes a `bed_id` the response structure is resolved up to the bed. If the caller passes a `ward_id`, just the organization and ward are resolved and returned via the response.

<details>
<summary>Example request and response</summary>

`GetBreadcrumbsRequest`
```json
{
  "room_id": "123"
}
```

`GetBreadcrumbsResponse`
```json
{
  "organization": {
    "id": "123",
    "name": "Organization A",
    "ward": {
      "id": "456",
      "name": "Ward A",
      "room": {
        "id": "789",
        "name": "Room A"
      }
    }
  }
}
```

</details>

### Why is this feature needed?

In our UI we have breadcrumbs with generic entity names. In the future, the UI should display the names of the entity instead of this generic name.

Bildschirm­foto 2023-08-19 um 10 58 45 PM

### Additional context

_`breadcrumb_svc.proto`_
```proto
syntax = "proto3";

package proto.services.task_svc.v1;

option go_package = "gen/proto/services/task-svc";

//
// GetBreadcrumbs
//

message GetBreadcrumbsRequest {
  optional string organization_id = 1;
  optional string ward_id = 2;
  optional string room_id = 3;
  optional string bed_id = 4;
  optional string patient_id = 5;
}

message GetBreadcrumbsResponse {
  optional Organization organization = 1;

  message Organization {
    string id = 1;
    string name = 2;
    optional Ward ward = 3;
  }

  message Ward {
    string id = 1;
    string name = 2;
    optional Room room = 3;
  }

  message Room {
    string id = 1;
    string name = 2;
    optional Bed bed = 3;
  }

  message Bed {
    string id = 1;
    string name = 2;
    optional Patient patient = 3;
  }

  message Patient {
    string id = 1;
    string name = 2;
  }
}

//
// BreadcrumbService
//

service BreadcrumbService {
  rpc GetBreadcrumbs(GetBreadcrumbsRequest) returns (GetBreadcrumbsResponse) {}
}
```

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #366

### CODE REVIEW

**Comment by DasProffi** [comment]
@Max how do we want to get the organization name? Do we wait for duplication to task service or do a service to service call for now?

**Comment by DasProffi** [comment]
I meant @MaxSchaefer
Sorry, for wrongly mentioning the other max

**Comment by MaxSchaefer** [comment]
@DasProffi sorry but we need to abandon this pull request. A bread crumb service is not really needed if we can just load the entity by ID including some more fields in the response.

**Comment by MaxSchaefer** [comment]
@DasProffi sorry but we need to abandon this pull request. A bread crumb service is not really needed if we can just load the entity by ID including some more fields in the response.

**Pull request closed without merging**
