### PR TITLE
fix: github-action token and name in CreateBedResponse

### PR DESCRIPTION
**Pull request by MaxSchaefer**
I've combine these changes to publish our packages

### CODE REVIEW

**Comment by use-to** [comment]
I saw this one...

**Comment by use-to** [comment]
@MaxSchaefer sus

**Comment by FoseFx** [comment]
What's better than unreviewed CI changes on holidays?

**Comment by MaxSchaefer** [comment]
... the failed CI was very unpleasant ... still red ...

**Pull request merged**
