### PR TITLE
feat: add multi_select to protos

### LINKED ISSUE #706: Add Multi-Select Datatype
### Describe the feature

The API needs to support Multi-Selects. A Multi-Selects is a (Single-)Select with more options.

### Why is this feature needed?

Currently, the API supports only (Single-)Selects. https://proto.helpwave.de/#proto.services.property_svc.v1.FieldType. web already implements Multi-Selects.

### Additional context

- https://pr-935-helpwave-web-tasks.fly.dev/properties
- We can discuss a potential rename of Select to Single-Select in this issue as well but should move the implementation to the future.

### LINKED ISSUE #762: Data-layer including tests
### Describe the chore

Integrate [testcontainers](https://testcontainers.org) or similar technology for more meaningful tests.
These should be used for "recipes", that test some part of a user's journey. For example: Add a property, add some rules, modify them, add values, then request attached properties.

### PR DESCRIPTION
**Pull request by FoseFx**
## Which issues does this pull request close?
closes #706

closes #762

<details>

<summary>ERD Prior</summary>

image

</details>

<details>

<summary>ERD Now</summary>

Screenshot from 2024-09-03 11-33-04

</details>

### CODE REVIEW

**Comment by MaxSchaefer** [comment]
@FoseFx current state of this pr?

**Review by MaxSchaefer — COMMENTED** [review]
I continue with manual tests

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
The introduction of Testcontainers should be also represented in our README

**Comment by FoseFx** [comment]
I can't keep keep merging main into this. @MaxSchaefer

**Review by MaxSchaefer — APPROVED** [review]
Very nice! Good job.
I like the Testcontainers integration. 👍

**Pull request merged**
